export * from "./branchesTable";
export * from "./employeesTable";
export * from "./ownersTable";
export * from "./shopOwnerTable";
export * from "./shopsTable";
export * from "./absentDetailsTable";
export * from "./deductionDetailsTable";
export * from "./incomeDetailsTable";
export * from "./otDetailsTable";
